# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: "Computação em Nuvem - 2025/2"
site_url: https://github.com/Insper/computacao-nuvem
site_author: Tiago Demay
site_description: >-
  Roteiros de aula para acesso ao conteudo

# Repository
repo_name: insper.github.io/computacao-nuvem
repo_url: https://github.com/Insper/computacao-nuvem

# Copyright
copyright: Copyright &copy; 2022 - Tiago Demay

# Configuration
theme:
  name: material
  custom_dir: !ENV [THEME_DIR, "material"]
  # features:
  #   - content.tabs.link
  #   - navigation.expand

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      background: white
      text: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: indigo
      background: '#2e3c43'
      text: white
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
  # palette:
  #   - scheme: default
  #     primary: teal
  #     accent: indigo
  #     toggle:
  #       icon: material/brightness-7
  #       name: Switch to dark mode
  #   - scheme: slate
  #     primary: teal
  #     accent: indigo
  #     toggle:
  #       icon: material/brightness-4
  #       name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        changelog/insiders.md: insiders/changelog.md
        conventions.md: philosophy.md
        reference/abbreviations.md: reference/tooltips.md
        reference/meta-tags.md: reference/index.md
        reference/variables.md: https://mkdocs-macros-plugin.readthedocs.io/
        sponsorship.md: insiders/index.md
        upgrading.md: upgrade.md
  - minify:
      minify_html: true

# Customization
extra:
  ihandout_config:
    #    counter:
    #      - question
    #      - tip
    #      - exercise
    #      - example
    report:
      api-base: https://devlife.insper-comp.com.br/api/offerings/1/
      url: https://devlife.insper-comp.com.br/api/offerings/1/exercises/

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Insper/computacao-nuvem
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tiago-demay

extra_css:
  - assets/stylesheets/extra.css
#  - https://cdn.jsdelivr.net/gh/insper-education/active-handout-css@main/devlife.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/insper-education/active-handout-plugins-js@main/package/plugin-bundle.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Roteiros:
    - Roteiro 1 MAAS: 
      - Objetivo : roteiros/1.objetivo.md
      - Infra: roteiros/1.infra.md
      - App: roteiros/1.app.md
    - Roteiro 2 JUJU:
      - Objetivo: roteiros/2.objetivo.md
      - Infra: roteiros/2.infra.md
      - App: roteiros/2.app.md
    - Roteiro 3 OpenStack: 
      - Objetivo: roteiros/3.objetivo.md
      - Infra: roteiros/3.infra.md
      - Setup: roteiros/3.setup.md
      - App: roteiros/3.app.md
    - Roteiro 4 SLA, DR e IaC:
      - Objetivo: roteiros/4.objetivo.md
      - Infra: roteiros/4.infra.md
      - App: roteiros/4.app.md
    - Roteiro 5 Docker e Kubernetes:
      - Objetivo: roteiros/5.objetivo.md
      - Infra: roteiros/5.infra.md
      - App: roteiros/5.app.md

  - Tutoriais:
    - Introdução: tutoriais/index.md
  
  - Plano de Aula:
    - metodologia: plano_aula/index.md

  - Projeto:
    - Introdução: projetos_2025-2/index.md

  - Arquivo:
    - Projetos 2022:
      - Francisco Janela: projetos_2022/fran-janela.md
      - Davi Reis: projetos_2022/DaviReisVieira.md
    - Projeto 2023:
      - Rubrica: projetos_2023/2023-2_projeto.md
      - Andre: projetos_2023/README_andre.md
      - Rodrigo: projetos_2023/README_rodrigo.md
    - Projeto 2024:
      - Rubrica: projetos_2024-1/2024-1_projeto.md
    - Projeto 2024-2:
      - Rubrica: projetos_2024-2/2024-2_projeto.md      
    - Projeto 2025-1:
      - Rubrica: projetos_2025-1/projeto.md      
    - Ligthsail:
        - Introdução: adicional/AWSLightsail.md
        - Instancia: adicional/topicos/AWSLigthsailInstancia.md
        - Administração: adicional/topicos/AWSLigthsailAdmin.md
        - Container: adicional/topicos/AWSLigthsailContainer.md

  - Conteudo adicional:
      - Cabeamento: 
        - Laboratório: adicional/0.Cabeamento.md
      - Governanca Internet: 
        - Videos: adicional/Videos_ref.md


